config/routes.rb
Rails.application.routes.draw do
    resources :categories
    resource :session
    resources :passwords, param: :token
    resources :tags
    # routes for users 
    resources :users, only: [:new, :create] 

    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
    # Can be used by load balancers and uptime monitors to verify that the app is live.
    get "up" => "rails/health#show", as: :rails_health_check

    # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
    # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
    # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

    # Defines the root path route ("/")
    # root "posts#index"
    root "products#index"

    # subscribe users to a specific product
    resources :products do
        resources :subscribers, only: [ :create ]
      end
    resource :unsubscribe, only: [ :show ]

    namespace :admin do
        resources :users
    end
    
end

app/models/tag.rb
class Tag < ApplicationRecord
    # prevents blank fields, duplicate tags
    validates :name, presence: true, uniqueness: {case_sensitive: false}

    has_many :product_tags, dependent: :destroy
    has_many :products, through: :product_tags
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    # callback method that runs "set_tag" method 
    # before edit, update and destroy, actions 
    # loads @tag based on its ID to avoid code repetition
    before_action :set_tag, only: [:edit, :update, :destroy, :show]

    # runs when /tags is visited 
    # fetches all tags from database and store them in @tags 
    def index 
        if params[:query].present? 
            @tags = Tag.where("name LIKE ?", "%#{params[:query]}%")
        else 
            @tags = Tag.all 
        end

        @tags = @tags.page(params[:page]).per(10)
    end

    def show
    end

    # prepares an empty tag object for the form in new.html.erb 
    def new 
        @tag = Tag.new 
    end

    # Creates a new tag with the form input (e.g. name).
    # tag_params filters which fields can be saved 
    def create 
        @tag = Tag.new(tag_params)
        # tries to save the tag to DB 
        if @tag.save
            redirect_to tags_path, notice: "Tag created successfully!"
        # display the form again and keep the error message
        else 
            render :new, status: :unprocessable_entity
        end
    end

    # loads tag for the edit form 
    def edit
    end

    # updates the selected tag with new values from the form 
    def update
        if @tag.update(tag_params)
            redirect_to tags_path, notice: "Tags updated successfully!"
        else 
            render :edit, status: unprocessable_entity
        end
    end

    # Deletes the selected tag from the database.
    def destroy
        @tag.destroy
        redirect_to tags_path, notice: "Tag deleted successfully!"
    end

    private
    # Finds the tag by its ID from the URL (like /tags/5/edit).
    # Assigns it to @tag so it can be used in edit, update, and destroy.
    def set_tag
        @tag = Tag.find(params[:id])
    end

    # strong parameters metod to prevent mass assignment 
    # allows name field in the form to be saved
    # protects the app from people trying to submit unwanted fields
    def tag_params
        params.require(:tag).permit(:name)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%# display error messages %>
<% if tag.errors.any? %>
    <div class="alert-box">
        <button class="close-btn" onclick="this.parentElement.style.display='none';">&times;</button>
        
        <p><%= pluralize(tag.errors.count, "error") %> prevented this tag from being saved:</p>
        <ul>
            <% tag.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<%= form_with model: tag do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <%= form.submit class: "btn btn-success" %>
<% end %>

app/views/tags/edit.html.erb
<h2>Edit Tag</h2>
<%= render 'form', tag: @tag %>

app/views/tags/index.html.erb
<div class="header-container">
    <h1 class= "page-title">Tags</h1>

    <div class="header-buttons"> 
       
        <% if Current.user&.role == "admin" %> 
            <%= link_to new_tag_path, class: "btn btn-success icon-spacing responsive-button" do %> 
                    <i class="fas fa-plus"></i>
                <span class="button-text">New</span>
            <% end %> 
        <% end %>

        <%= form_with url: tags_path, method: :get, local: true, class: "search-form" do %>
            <div class="search-wrapper">
                <%= text_field_tag :query, params[:query], placeholder: "Search tags...", class: "search-input" %>
                <button type="submit" class="search-icon-btn">
                <i class="fas fa-search"></i>
                </button>
            </div>
        <% end %>
    </div> 
</div> 

<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <% if @tags.any? %> 
        <% @tags.each_with_index do |tag, index| %>
        <tr onclick="window.location='<%= tag_path(tag) %>'" style="cursor: pointer;">
            <td class="counter-col"> <%= @tags.offset_value + index + 1 %></td>
            <td><%= tag.name %></td>
        </tr>
        <% end %>
    <% else %>
        <tr> 
            <td colspan="2" class= "text-center text-muted"> No tags found. </td>  
        </tr> 
    <% end %>
  </tbody>
</table>

<div class="pagination-stack-wrapper"> 
    <%# Pagination summary %>
    <% if @tags.total_count > 0 %>
        <div class="pagination-summary text-muted text-end">
            Showing <%= @tags.offset_value + 1 %>–
            <%= [@tags.offset_value + @tags.limit_value, @tags.total_count].min %>
            of <%= @tags.total_count %> tags
        </div>
    <% end %>

    <%# Pagination controls %>
    <div class="pagination-controls">
        <%= paginate @tags %>
    </div> 
</div>

app/views/tags/new.html.erb
<h2>New Tag</h2>
<%= render 'form', tag: @tag %>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>



<div class="category-buttons">


    <%= link_to "Back to tags", tags_path, class: "btn back" %>

    <% if Current.user&.role == "admin" %>     
        <%= link_to "Edit", edit_tag_path(@tag), class: "btn btn-primary" %>
        <%= button_to "Delete", @tag, method: :delete, data: { confirm: "Are you sure?" }, class: "btn delete" %>
    <% end %>
</div>