config/routes.rb
Rails.application.routes.draw do
    resources :categories
    resource :session
    resources :passwords, param: :token
    resources :tags
    # routes for users 
    resources :users, only: [:new, :create] 

    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
    # Can be used by load balancers and uptime monitors to verify that the app is live.
    get "up" => "rails/health#show", as: :rails_health_check

    # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
    # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
    # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

    # Defines the root path route ("/")
    # root "posts#index"
    root "products#index"

    # subscribe users to a specific product
    resources :products do
        resources :subscribers, only: [ :create ]
      end
    resource :unsubscribe, only: [ :show ]

    namespace :admin do
        resources :users
    end
    
end

app/views/layouts/application.html.erb
<%= stylesheet_link_tag "custom_login", media: "all" %>
<%= stylesheet_link_tag "register", media: "all" %>

<!DOCTYPE html>
<html>
  <head>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <title><%= content_for(:title) || "Store" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA /////////////////////////manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" integrity="sha512-..." crossorigin="anonymous" referrerpolicy="no-referrer" />
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/15.7.0/nouislider.min.css">

    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css", crossorigin: "anonymous" %>
    <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js", crossorigin: "anonymous" %>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js" %>
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" %>

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/15.7.0/nouislider.min.js"></script>
    
  </head>

  <body>
    <nav class="top-nav">
        <div class="left">
            <%= link_to "Home", root_path %>
        </div>

        <div class="right"> 
            <% if authenticated? %>
                <%= link_to "Admin Panel", admin_users_path %>
                <%= link_to "Categories", categories_path %>
                <%= link_to "Tags", tags_path %>
                <%= button_to "Log out", session_path, method: :delete if authenticated? %>
            <% else %> 
                <%= link_to "Sign up", new_user_path %> |
                <%= link_to "Login", new_session_path unless authenticated? %>
            <% end %>
         
        </div> 
    </nav>
    
    <%= render 'shared/flash' %>
    
    <main>
        <%= yield %>
    </main>

    <% if Current.user.present? %>
        <div class="logged-in-indicator"> 
            Logged in as: <strong> <%= Current.user.full_name %> </strong> (<%= Current.user.role %>)
        </div>
    <% end %> 
  </body>
</html>

<script>
  setTimeout(() => {
    document.querySelectorAll('.alert').forEach(alert => {
      alert.style.transition = "opacity 1s ease-out";
      alert.style.opacity = "0"; // gradually fades out

      // Remove from DOM after fade completes
      setTimeout(() => alert.remove(), 1000);
    });
  }, 5000); // delay before fading starts

    // allows users to select new category field
    document.addEventListener("DOMContentLoaded", function () {
        const select = document.getElementById("category-select");
        const newField = document.getElementById("new-category-field");

        select.addEventListener("change", function () {
            if (select.value === "") {
            newField.style.display = "block";
            } else {
            newField.style.display = "none";
            }
        });
    });

</script>